// <auto-generated />
using EmployeeManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManager.Core.Entities.Employee.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test1@gmail.com",
                            FirstName = "Mahmoud",
                            ImageUrl = "Images/EmployeePersonalImage/test1.jpg",
                            LastName = "Abd Elaziz",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test2@gmail.com",
                            FirstName = "Malak",
                            ImageUrl = "Images/EmployeePersonalImage/test2.jpg",
                            LastName = "Gamal",
                            Position = "Network Engineer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test3@gmail.com",
                            FirstName = "Yassen",
                            ImageUrl = "Images/EmployeePersonalImage/test3.jpg",
                            LastName = "Walid",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            Id = 4,
                            Email = "test4@gmail.com",
                            FirstName = "Mahmoud",
                            ImageUrl = "Images/EmployeePersonalImage/test4.jpg",
                            LastName = "Wael",
                            Position = "Markting"
                        },
                        new
                        {
                            Id = 5,
                            Email = "test5@gmail.com",
                            FirstName = "Mansour",
                            ImageUrl = "Images/EmployeePersonalImage/test5.jpg",
                            LastName = "Mohamed",
                            Position = "Technical Support"
                        },
                        new
                        {
                            Id = 6,
                            Email = "test6@gmail.com",
                            FirstName = "Ahmed",
                            ImageUrl = "Images/EmployeePersonalImage/test6.jpg",
                            LastName = "Gmal",
                            Position = "HR Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
